// ─── Discord Interaction Types ────────────────────────────────────────────────

export type InteractionType = 1 | 2 | 3 | 5;

export interface DiscordUser {
  id: string;
  username: string;
  discriminator: string;
  global_name: string | null;
  avatar: string | null;
}

export interface DiscordMember {
  user: DiscordUser;
  roles: string[];
  joined_at: string;
  nick: string | null;
}

export interface DiscordCommandOption {
  name: string;
  type: number;
  value?: string | number | boolean;
  options?: DiscordCommandOption[];
}

export interface DiscordApplicationCommandData {
  id: string;
  name: string;
  type: number;
  options?: DiscordCommandOption[];
}

export interface DiscordInteraction {
  id: string;
  application_id: string;
  type: InteractionType;
  data?: DiscordApplicationCommandData;
  guild_id?: string;
  channel_id?: string;
  member?: DiscordMember;
  user?: DiscordUser;
  token: string;
  version: number;
}

// ─── Queue Event Types ────────────────────────────────────────────────────────

/**
 * INTERACTION — slash command sent by a user in Discord.
 * AI rule: summarize/tag the command text.
 */
export interface InteractionQueueEvent {
  kind: "INTERACTION";
  interactionId: string;
  guildId: string | null;
  channelId: string | null;
  userId: string;
  username: string;
  commandName: string;
  commandOptions: DiscordCommandOption[];
  token: string;
  applicationId: string;
  receivedAt: string; // ISO timestamp
}

/**
 * BOT_MESSAGE — a normal message the bot wants to send to a channel.
 * AI rule: classify intent, format/enrich the message content.
 * No interaction token. No Slack mirror by default.
 */
export interface BotMessageQueueEvent {
  kind: "BOT_MESSAGE";
  messageId: string;         // unique ID generated by the bot, used for dedup
  channelId: string;
  guildId: string | null;
  content: string;
  triggeredBy: string | null; // optional: which user/action triggered it
  aiEnrich: boolean;          // whether to run AI enrichment before sending
  receivedAt: string;         // ISO timestamp
}

export interface BotReplyQueueEvent {
  kind: "BOT_REPLY";
  interactionId: string;
  token: string;
  applicationId: string;
  content: string;
  retryCount: number;
}

export interface MirrorQueueEvent {
  kind: "MIRROR";
  interactionId: string;
  commandName: string;
  username: string;
  guildId: string | null;
  content: string;
  retryCount: number;
}

export type QueueEventKind = "INTERACTION" | "BOT_MESSAGE" | "BOT_REPLY" | "MIRROR";
export type QueueEvent =
  | InteractionQueueEvent
  | BotMessageQueueEvent
  | BotReplyQueueEvent
  | MirrorQueueEvent;

// ─── Processing State (idempotency) ──────────────────────────────────────────

/**
 * Tracks the processing stage of each event in Redis.
 * Allows crash recovery without re-doing completed steps.
 *
 * State machine:
 *   claimed → discord_done → slack_done → ai_done → db_queued → done
 *
 * For BOT_MESSAGE:
 *   claimed → ai_done → discord_done → db_queued → done
 */
export type ProcessingState =
  | "claimed"       // worker has started; key TTL = 60s (expires if worker crashes)
  | "discord_done"  // Discord reply/send succeeded
  | "slack_done"    // Slack mirror succeeded (INTERACTION only)
  | "ai_done"       // AI step succeeded
  | "db_queued"     // DB write has been added to the batch buffer
  | "done";         // DB flushed, ack'd — key TTL extended to 24h

// ─── Database Row Types ───────────────────────────────────────────────────────

export type InteractionStatus = "PENDING" | "PROCESSED" | "FAILED" | "DEDUPLICATED";
export type ActionType = "BOT_REPLY" | "MIRROR_SLACK" | "MIRROR_DISCORD" | "AI_TAG";
export type ActionStatus = "SUCCESS" | "FAILED" | "RETRYING" | "DLQ";

export interface DbInteraction {
  id: string;
  interactionId: string;
  guildId: string | null;
  channelId: string | null;
  userId: string;
  username: string;
  commandName: string;
  commandOptions: DiscordCommandOption[];
  status: InteractionStatus;
  receivedAt: Date;
  processedAt: Date | null;
  aiSummary: string | null;
  aiTags: string[];
}

export interface DbAction {
  id: string;
  interactionDbId: string;
  type: ActionType;
  status: ActionStatus;
  payload: Record<string, unknown>;
  retryCount: number;
  error: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface DbCommandConfig {
  id: string;
  guildId: string;
  commandName: string;
  isEnabled: boolean;
  mirrorEnabled: boolean;
  aiEnabled: boolean;
  customResponse: string | null;
  updatedAt: Date;
}

export interface DbAdminSession {
  id: string;
  userId: string;
  email: string;
  token: string;
  expiresAt: Date;
  createdAt: Date;
}

// ─── API Response Types ───────────────────────────────────────────────────────

export interface ApiSuccess<T> {
  success: true;
  data: T;
}

export interface ApiError {
  success: false;
  error: string;
  code?: string;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiError;

// ─── Dashboard Types ──────────────────────────────────────────────────────────

export interface DashboardStats {
  totalInteractions: number;
  successfulActions: number;
  failedActions: number;
  dlqCount: number;
  activeGuilds: number;
}

export interface InteractionLogEntry extends DbInteraction {
  actions: DbAction[];
}

// ─── Redis Stream Types ───────────────────────────────────────────────────────

export type StreamName = "interactions" | "bot-messages" | "bot-replies" | "mirrors" | "dlq";

export interface StreamMessage<T extends QueueEvent> {
  id: string;
  data: T;
}

// ─── Batch Writer Types ───────────────────────────────────────────────────────

/** A pending DB write for an Interaction record, queued by the batch writer. */
export interface PendingInteractionWrite {
  interactionId: string;
  guildId: string | null;
  channelId: string | null;
  userId: string;
  username: string;
  commandName: string;
  commandOptions: DiscordCommandOption[];
  status: InteractionStatus;
  receivedAt: Date;
  processedAt: Date | null;
  aiSummary: string | null;
  aiTags: string[];
}

/** A pending DB write for an Action record, queued by the batch writer. */
export interface PendingActionWrite {
  interactionId: string; // Discord interaction ID (not DB id)
  type: ActionType;
  status: ActionStatus;
  payload: Record<string, unknown>;
  retryCount: number;
  error: string | null;
}

// ─── User Session (Redis LRU) ─────────────────────────────────────────────────

/**
 * Per-user, per-channel session stored in Redis with TTL.
 * Provides AI context across multiple questions in the same session.
 *
 * LRU eviction: Redis TTL is refreshed on every interaction.
 * Session expires after SESSION_TTL seconds of inactivity.
 *
 * Key: session:{userId}:{channelId}
 */
export interface UserSession {
  userId: string;
  username: string;
  channelId: string;
  guildId: string | null;
  /** Rolling summary of the conversation so far, updated by AI each turn. */
  recentSummary: string | null;
  /** Last N message contents — sent as context window to the AI. */
  contextMessages: string[];
  /** Total interactions in this session. */
  messageCount: number;
  /** ISO timestamp of last activity. */
  lastActivity: string;
}

// ─── Auth ─────────────────────────────────────────────────────────────────────

export interface AdminLoginRequest {
  email: string;
  password: string;
}

export interface AdminLoginResponse {
  token: string;
  expiresAt: string;
}
